/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type SharedSections = {
  _id: string;
  _type: "sharedSections";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  coreValues?: {
    eyebrow: string;
    title: string;
  };
  reviewSummary?: {
    count: string;
    rating: string;
    source: string;
  };
};

export type FirmStats = {
  _id: string;
  _type: "firmStats";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stats: Array<{
    big: string;
    label: string;
    _key: string;
  }>;
};

export type ContactSettings = {
  _id: string;
  _type: "contactSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow: string;
  title: string;
  reassurances?: Array<string>;
  callPrompt?: string;
  callBadge?: string;
  form?: {
    title: string;
    lede?: string;
    submitLabel: string;
    disclaimer?: string;
  };
  photoAlt?: string;
  callCard?: {
    label: string;
    note?: string;
  };
  textCard?: {
    label: string;
    note?: string;
  };
  emailCard?: {
    label: string;
    note?: string;
  };
  officeCard?: {
    label: string;
    note?: string;
  };
  hours?: {
    label: string;
    note?: string;
  };
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  aboutMenu?: Array<
    {
      _key: string;
    } & NavLink
  >;
  practiceAreasMenu?: Array<
    {
      _key: string;
    } & NavLink
  >;
  locationsMenu?: Array<
    {
      _key: string;
    } & NavLink
  >;
  footerPracticeAreas?: Array<
    {
      _key: string;
    } & NavLink
  >;
  footerNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  serviceAreas?: Array<string>;
};

export type FirmDetails = {
  _id: string;
  _type: "firmDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  legalName: string;
  phone: string;
  sms: string;
  email?: string;
  address: {
    street: string;
    unit?: string;
    city: string;
    region: string;
    postalCode: string;
    country: string;
  };
  geo: Geopoint;
  mapUrl: string;
  mapPlaceCid: string;
  hoursDisplay: string;
  hours: string;
  socials?: Array<{
    name: "facebook" | "linkedin" | "youtube" | "tiktok" | "instagram";
    href: string;
    _key: string;
  }>;
  directoryProfiles?: Array<string>;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key: Slug;
  name: string;
  format: "video" | "written";
  video?: VideoRef;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  length?: string;
  quote: string;
  body?: string;
  source?: "google";
  onReviewsPage?: boolean;
  reviewOrder?: number;
  onHomeRail?: boolean;
  railOrder?: number;
  railHeadline?: string;
  railBody?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type VideoRef = {
  _type: "videoRef";
  provider: "wistia" | "youtube";
  id: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  shownOn: "home" | "car-accidents";
  video: VideoRef;
  videoLength: string;
  order: number;
};

export type CoreValue = {
  _id: string;
  _type: "coreValue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  body: string;
  iconKey:
    | "commitment"
    | "integrity"
    | "compassion"
    | "community"
    | "innovation"
    | "teamwork";
  order: number;
};

export type CaseResult = {
  _id: string;
  _type: "caseResult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tag: string;
  recovered: string;
  offered: string;
  badge:
    | "Trial Win"
    | "Settlement"
    | "Judgment"
    | "Trial Counsel"
    | "Co-Counsel"
    | "Local Counsel";
  wonInCourt?: boolean;
  story: string;
  shownOn: "results" | "co-counsel" | "home";
  order: number;
};

export type Award = {
  _id: string;
  _type: "award";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key: Slug;
  alt: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  height: number;
  order: number;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type InlineText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SimpleText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type NavLink = {
  _type: "navLink";
  label: string;
  href: string;
};

export type Link = {
  _type: "link";
  href?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SharedSections
  | FirmStats
  | ContactSettings
  | Navigation
  | FirmDetails
  | Geopoint
  | SanityImageAssetReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | VideoRef
  | Slug
  | Faq
  | CoreValue
  | CaseResult
  | Award
  | Seo
  | InlineText
  | SimpleText
  | RichText
  | NavLink
  | Link
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: src/sanity/lib/queries.ts
// Variable: FIRM_DETAILS_QUERY
// Query: *[_type == "firmDetails" && _id == "firmDetails"][0]{  name,  legalName,  phone,  sms,  email,  address{ street, unit, city, region, postalCode, country },  "geo": { "lat": geo.lat, "lng": geo.lng },  mapUrl,  mapPlaceCid,  hours,  hoursDisplay,  socials[]{ name, href },  "directoryProfiles": coalesce(directoryProfiles, [])}
export type FIRM_DETAILS_QUERY_RESULT = {
  name: string;
  legalName: string;
  phone: string;
  sms: string;
  email: string | null;
  address: {
    street: string;
    unit: string | null;
    city: string;
    region: string;
    postalCode: string;
    country: string;
  };
  geo: {
    lat: number | null;
    lng: number | null;
  };
  mapUrl: string;
  mapPlaceCid: string;
  hours: string;
  hoursDisplay: string;
  socials: Array<{
    name: "facebook" | "instagram" | "linkedin" | "tiktok" | "youtube";
    href: string;
  }> | null;
  directoryProfiles: Array<string> | Array<never>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation" && _id == "navigation"][0]{  "aboutMenu": coalesce(aboutMenu[]{ label, href }, []),  "practiceAreasMenu": coalesce(practiceAreasMenu[]{ label, href }, []),  "locationsMenu": coalesce(locationsMenu[]{ label, href }, []),  "footerPracticeAreas": coalesce(footerPracticeAreas[]{ label, href }, []),  "footerNav": coalesce(footerNav[]{ label, href }, []),  "serviceAreas": coalesce(serviceAreas, [])}
export type NAVIGATION_QUERY_RESULT = {
  aboutMenu:
    | Array<{
        label: string;
        href: string;
      }>
    | Array<never>;
  practiceAreasMenu:
    | Array<{
        label: string;
        href: string;
      }>
    | Array<never>;
  locationsMenu:
    | Array<{
        label: string;
        href: string;
      }>
    | Array<never>;
  footerPracticeAreas:
    | Array<{
        label: string;
        href: string;
      }>
    | Array<never>;
  footerNav:
    | Array<{
        label: string;
        href: string;
      }>
    | Array<never>;
  serviceAreas: Array<string> | Array<never>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CONTACT_SETTINGS_QUERY
// Query: *[_type == "contactSettings" && _id == "contactSettings"][0]{  eyebrow,  title,  "reassurances": coalesce(reassurances, []),  callPrompt,  callBadge,  form{ title, lede, submitLabel, disclaimer },  photoAlt,  callCard{ label, note },  textCard{ label, note },  emailCard{ label, note },  officeCard{ label, note },  hours{ label, note }}
export type CONTACT_SETTINGS_QUERY_RESULT = {
  eyebrow: string;
  title: string;
  reassurances: Array<string> | Array<never>;
  callPrompt: string | null;
  callBadge: string | null;
  form: {
    title: string;
    lede: string | null;
    submitLabel: string;
    disclaimer: string | null;
  } | null;
  photoAlt: string | null;
  callCard: {
    label: string;
    note: string | null;
  } | null;
  textCard: {
    label: string;
    note: string | null;
  } | null;
  emailCard: {
    label: string;
    note: string | null;
  } | null;
  officeCard: {
    label: string;
    note: string | null;
  } | null;
  hours: {
    label: string;
    note: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: FIRM_STATS_QUERY
// Query: *[_type == "firmStats" && _id == "firmStats"][0]{  "stats": coalesce(stats[]{ _key, big, label }, [])}
export type FIRM_STATS_QUERY_RESULT = {
  stats: Array<{
    _key: string;
    big: string;
    label: string;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: AWARDS_QUERY
// Query: *[_type == "award"] | order(order asc){  "_key": key.current,  alt,  image,  height}
export type AWARDS_QUERY_RESULT = Array<{
  _key: string;
  alt: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  height: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CORE_VALUES_QUERY
// Query: *[_type == "coreValue"] | order(order asc){  "_key": _id,  title,  body,  iconKey}
export type CORE_VALUES_QUERY_RESULT = Array<{
  _key: string;
  title: string;
  body: string;
  iconKey:
    | "commitment"
    | "community"
    | "compassion"
    | "innovation"
    | "integrity"
    | "teamwork";
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SHARED_SECTIONS_QUERY
// Query: *[_type == "sharedSections" && _id == "sharedSections"][0]{  coreValues{ eyebrow, title },  reviewSummary{ count, rating, source }}
export type SHARED_SECTIONS_QUERY_RESULT = {
  coreValues: {
    eyebrow: string;
    title: string;
  } | null;
  reviewSummary: {
    count: string;
    rating: string;
    source: string;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_FAQS_QUERY
// Query: *[_type == "faq" && shownOn == "home"]  | order(order asc){  "_key": _id,  question,  answer,  videoLength,  video{ provider, id }}
export type HOME_FAQS_QUERY_RESULT = Array<{
  _key: string;
  question: string;
  answer: string;
  videoLength: string;
  video: {
    provider: "wistia" | "youtube";
    id: string;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CAR_ACCIDENT_FAQS_QUERY
// Query: *[_type == "faq" && shownOn == "car-accidents"] | order(order asc){  "_key": _id,  question,  answer,  videoLength,  video{ provider, id }}
export type CAR_ACCIDENT_FAQS_QUERY_RESULT = Array<{
  _key: string;
  question: string;
  answer: string;
  videoLength: string;
  video: {
    provider: "wistia" | "youtube";
    id: string;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CASE_RESULTS_QUERY
// Query: *[_type == "caseResult" && shownOn == "results"] | order(order asc){  "_key": _id, tag, badge, "wonInCourt": coalesce(wonInCourt, false), offered, recovered, story}
export type CASE_RESULTS_QUERY_RESULT = Array<{
  _key: string;
  tag: string;
  badge:
    | "Co-Counsel"
    | "Judgment"
    | "Local Counsel"
    | "Settlement"
    | "Trial Counsel"
    | "Trial Win";
  wonInCourt: boolean | false;
  offered: string;
  recovered: string;
  story: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CO_COUNSEL_RESULTS_QUERY
// Query: *[_type == "caseResult" && shownOn == "co-counsel"] | order(order asc){  "_key": _id, tag, badge, "wonInCourt": coalesce(wonInCourt, false), offered, recovered, story}
export type CO_COUNSEL_RESULTS_QUERY_RESULT = Array<{
  _key: string;
  tag: string;
  badge:
    | "Co-Counsel"
    | "Judgment"
    | "Local Counsel"
    | "Settlement"
    | "Trial Counsel"
    | "Trial Win";
  wonInCourt: boolean | false;
  offered: string;
  recovered: string;
  story: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_RESULTS_QUERY
// Query: *[_type == "caseResult" && shownOn == "home"] | order(order asc){  "_key": _id, tag, badge, "wonInCourt": coalesce(wonInCourt, false), offered, recovered, story}
export type HOME_RESULTS_QUERY_RESULT = Array<{
  _key: string;
  tag: string;
  badge:
    | "Co-Counsel"
    | "Judgment"
    | "Local Counsel"
    | "Settlement"
    | "Trial Counsel"
    | "Trial Win";
  wonInCourt: boolean | false;
  offered: string;
  recovered: string;
  story: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && onHomeRail == true] | order(railOrder asc){  "_key": key.current,  "kind": select(format == "video" => "video", "quote"),  name,  video{ provider, id },  poster,  length,  "headline": railHeadline,  "body": railBody}
export type HOME_TESTIMONIALS_QUERY_RESULT = Array<{
  _key: string;
  kind: "quote" | "video";
  name: string;
  video: {
    provider: "wistia" | "youtube";
    id: string;
  } | null;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  length: string | null;
  headline: string | null;
  body: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: VIDEO_REVIEWS_QUERY
// Query: *[_type == "testimonial" && onReviewsPage == true && format == "video"]  | order(reviewOrder asc){  "_key": key.current,  video{ provider, id },  name,  quote,  poster}
export type VIDEO_REVIEWS_QUERY_RESULT = Array<{
  _key: string;
  video: {
    provider: "wistia" | "youtube";
    id: string;
  } | null;
  name: string;
  quote: string;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: WRITTEN_REVIEWS_QUERY
// Query: *[_type == "testimonial" && onReviewsPage == true && format == "written"]  | order(reviewOrder asc){  "_key": key.current,  name,  source,  quote,  body}
export type WRITTEN_REVIEWS_QUERY_RESULT = Array<{
  _key: string;
  name: string;
  source: "google" | null;
  quote: string;
  body: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "firmDetails" && _id == "firmDetails"][0]{\n  name,\n  legalName,\n  phone,\n  sms,\n  email,\n  address{ street, unit, city, region, postalCode, country },\n  "geo": { "lat": geo.lat, "lng": geo.lng },\n  mapUrl,\n  mapPlaceCid,\n  hours,\n  hoursDisplay,\n  socials[]{ name, href },\n  "directoryProfiles": coalesce(directoryProfiles, [])\n}': FIRM_DETAILS_QUERY_RESULT;
    '*[_type == "navigation" && _id == "navigation"][0]{\n  "aboutMenu": coalesce(aboutMenu[]{ label, href }, []),\n  "practiceAreasMenu": coalesce(practiceAreasMenu[]{ label, href }, []),\n  "locationsMenu": coalesce(locationsMenu[]{ label, href }, []),\n  "footerPracticeAreas": coalesce(footerPracticeAreas[]{ label, href }, []),\n  "footerNav": coalesce(footerNav[]{ label, href }, []),\n  "serviceAreas": coalesce(serviceAreas, [])\n}': NAVIGATION_QUERY_RESULT;
    '*[_type == "contactSettings" && _id == "contactSettings"][0]{\n  eyebrow,\n  title,\n  "reassurances": coalesce(reassurances, []),\n  callPrompt,\n  callBadge,\n  form{ title, lede, submitLabel, disclaimer },\n  photoAlt,\n  callCard{ label, note },\n  textCard{ label, note },\n  emailCard{ label, note },\n  officeCard{ label, note },\n  hours{ label, note }\n}': CONTACT_SETTINGS_QUERY_RESULT;
    '*[_type == "firmStats" && _id == "firmStats"][0]{\n  "stats": coalesce(stats[]{ _key, big, label }, [])\n}': FIRM_STATS_QUERY_RESULT;
    '*[_type == "award"] | order(order asc){\n  "_key": key.current,\n  alt,\n  image,\n  height\n}': AWARDS_QUERY_RESULT;
    '*[_type == "coreValue"] | order(order asc){\n  "_key": _id,\n  title,\n  body,\n  iconKey\n}': CORE_VALUES_QUERY_RESULT;
    '*[_type == "sharedSections" && _id == "sharedSections"][0]{\n  coreValues{ eyebrow, title },\n  reviewSummary{ count, rating, source }\n}': SHARED_SECTIONS_QUERY_RESULT;
    '*[_type == "faq" && shownOn == "home"]\n  | order(order asc){\n  "_key": _id,\n  question,\n  answer,\n  videoLength,\n  video{ provider, id }\n}': HOME_FAQS_QUERY_RESULT;
    '*[_type == "faq" && shownOn == "car-accidents"] | order(order asc){\n  "_key": _id,\n  question,\n  answer,\n  videoLength,\n  video{ provider, id }\n}': CAR_ACCIDENT_FAQS_QUERY_RESULT;
    '*[_type == "caseResult" && shownOn == "results"] | order(order asc){\n  "_key": _id, tag, badge, "wonInCourt": coalesce(wonInCourt, false), offered, recovered, story\n}': CASE_RESULTS_QUERY_RESULT;
    '*[_type == "caseResult" && shownOn == "co-counsel"] | order(order asc){\n  "_key": _id, tag, badge, "wonInCourt": coalesce(wonInCourt, false), offered, recovered, story\n}': CO_COUNSEL_RESULTS_QUERY_RESULT;
    '*[_type == "caseResult" && shownOn == "home"] | order(order asc){\n  "_key": _id, tag, badge, "wonInCourt": coalesce(wonInCourt, false), offered, recovered, story\n}': HOME_RESULTS_QUERY_RESULT;
    '*[_type == "testimonial" && onHomeRail == true] | order(railOrder asc){\n  "_key": key.current,\n  "kind": select(format == "video" => "video", "quote"),\n  name,\n  video{ provider, id },\n  poster,\n  length,\n  "headline": railHeadline,\n  "body": railBody\n}': HOME_TESTIMONIALS_QUERY_RESULT;
    '*[_type == "testimonial" && onReviewsPage == true && format == "video"]\n  | order(reviewOrder asc){\n  "_key": key.current,\n  video{ provider, id },\n  name,\n  quote,\n  poster\n}': VIDEO_REVIEWS_QUERY_RESULT;
    '*[_type == "testimonial" && onReviewsPage == true && format == "written"]\n  | order(reviewOrder asc){\n  "_key": key.current,\n  name,\n  source,\n  quote,\n  body\n}': WRITTEN_REVIEWS_QUERY_RESULT;
  }
}
